### ISSUE TITLE
Lab file with the answers

### ISSUE THREAD

**Issue by Felipe-Hub** [ironhack-labs/lab-macros-automated-report-generation#1]
@sandrabosk 
In the file for the lab, the macros with the final output is already there.

**Comment by ironhack-edu** [comment]
@haggarw3 was this fixed? I think yes, but I am not sure. Thank you!! 😉

**Comment by ironhack-edu** [comment]
Closed with [commit: 92711976ba9cc710ef0d23ff8dc3a3a835c53f7b](https://github.com/ironhack-labs/lab-macros-automated-report-generation/commit/92711976ba9cc710ef0d23ff8dc3a3a835c53f7b)
